# Generated by Django 3.2.13 on 2022-04-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0HfIfLCRJFqixc-gE5AW-VvVpSRTGocuTVA&usqp=CAU', max_length=1500),
        ),
    ]
